// @ts-check
/**
 * client/ lint rules.
 *
 * `pnpm lint` runs with `--max-warnings 0`, so severity here is documentation of
 * intent, not of strictness — every finding fails the build either way. The
 * split still matters when triaging:
 *
 *  - `error` — a bug or a rule violation with no legitimate exception.
 *  - `warn`  — a boundary the repo has agreed on but where a considered
 *              exception could be argued in review.
 *
 * The tree was brought to zero when these rules landed, so there is no
 * suppression baseline to maintain (unlike the server's dependency-cruiser
 * known-violations file). Keep it that way: fix the finding, don't raise a cap.
 *
 * See .claude/skills/frontend-architecture/ for the conventions being encoded.
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';

export default tseslint.config(
  {
    // Vendored trees are not ours to lint; .next is build output;
    // next-env.d.ts is generated by Next on every build.
    ignores: [
      '.next/**',
      'node_modules/**',
      'src/vendor/**',
      'next.config.mjs',
      'next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      '@next/next': nextPlugin,
    },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,

      // --- hooks ---------------------------------------------------------
      // rules-of-hooks is non-negotiable: violating it is a runtime bug.
      'react-hooks/rules-of-hooks': 'error',
      // exhaustive-deps is warn: ConfigTab/RunStatus/ReviewRunAccordion carry
      // deliberate inline disables today. Ratcheted, not ignored.
      'react-hooks/exhaustive-deps': 'warn',

      // --- direction rule ------------------------------------------------
      // shared → features is the coupling bug worth linting for. The reverse
      // (a route importing a shared component) is the intended direction.
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            {
              group: ['**/app/**'],
              message:
                'src/components and src/lib are the shared layer — they must not import from src/app. ' +
                'Move the shared part down, or compose in the route.',
            },
            {
              group: ['../../../../*'],
              message:
                'Import depth ≥4 — use the "@/" alias (configured in tsconfig.json and vitest.config.ts).',
            },
          ],
        },
      ],

      // --- noise control -------------------------------------------------
      // The codebase uses `_`-prefixed throwaways; everything else is real.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
    },
  },

  {
    // The shared layer is the side the direction rule actually constrains.
    files: ['src/components/**/*.{ts,tsx}', 'src/lib/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/app/**', '@/app/**'],
              message:
                'Shared code must not depend on a route. Invert: take props/generics, ' +
                'and let the route supply the concrete shapes.',
            },
          ],
        },
      ],
    },
  },

  {
    // Tests may reach anywhere and lean on loose typing.
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-restricted-imports': 'off',
    },
  },
);
