import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard. */
export const s = {
  card: (status: string): CSSProperties => ({
    display: "flex",
    gap: 16,
    padding: 16,
    borderRadius: 10,
    border: "1px solid " + (status === "accepted" ? "var(--accent)" : "var(--border)"),
    background: "var(--bg-elevated)",
    opacity: status === "rejected" ? 0.55 : 1,
    marginBottom: 12,
  }),
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  ruleRow: { display: "flex", alignItems: "flex-start", gap: 8 } satisfies CSSProperties,
  rule: {
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.45,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    padding: 4,
    flexShrink: 0,
  } satisfies CSSProperties,
  editRow: { display: "flex", gap: 8, marginTop: 8 } satisfies CSSProperties,
  editError: {
    marginTop: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 12.5,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: "7px 7px 0 0",
    border: "1px solid var(--border)",
    borderBottom: "none",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  evidencePath: {
    fontSize: 12,
    color: "var(--text-secondary)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--text-primary)",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: "0 0 7px 7px",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  confidenceLabel: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  confidenceBar: { flex: 1, maxWidth: 180 } satisfies CSSProperties,
  confidenceValue: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-primary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  side: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: 132,
    flexShrink: 0,
  } satisfies CSSProperties,
} as const;
