import type { CSSProperties } from "react";

/** Co-located styles for ContextTab. Mirrors SkillsTab/styles.ts token usage. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  tokenEstimate: {
    fontSize: 12,
    color: "var(--text-secondary)",
    marginBottom: 14,
  } satisfies CSSProperties,
  repoRow: { marginBottom: 14, maxWidth: 320 } satisfies CSSProperties,
  filterRow: { marginBottom: 14 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 12, padding: "10px 12px", borderRadius: 8, border: "1px solid var(--border)", background: "var(--bg-elevated)" } satisfies CSSProperties,
  rowBroken: { borderColor: "var(--crit)" } satisfies CSSProperties,
  rowMain: { display: "flex", alignItems: "center", gap: 10, flex: 1, minWidth: 0 } satisfies CSSProperties,
  name: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  order: { fontSize: 12, color: "var(--text-muted)", width: 20, textAlign: "right" } satisfies CSSProperties,
  reorderBtns: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  reorderDisabled: { opacity: 0.35, pointerEvents: "none" } satisfies CSSProperties,
  rowActions: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  actions: { display: "flex", gap: 10, marginTop: 10 } satisfies CSSProperties,
  savedNote: { alignSelf: "center", fontSize: 13, color: "var(--ok)" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "12px 0" } satisfies CSSProperties,
  inheritedSection: { marginTop: 4, marginBottom: 20 } satisfies CSSProperties,
  inheritedTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 8,
  } satisfies CSSProperties,
  inheritedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px dashed var(--border)",
    background: "var(--bg-hover)",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
